--CRIAR TABELAS

CREATE TABLE CLIENTE(
	CLIENTE_ID			INT				NOT NULL	PRIMARY KEY IDENTITY,	
	CLIENTE				VARCHAR(50)		NOT NULL,
	EMAIL				VARCHAR(100)	NOT NULL,
	TELEFONE			VARCHAR(15)		NOT NULL	
);

CREATE TABLE FORNECEDOR(
	FORNECEDOR_ID		INT				NOT NULL	PRIMARY KEY IDENTITY,
	RAZAO_SOCIAL		VARCHAR(100)	NOT NULL,
	TELEFONE			VARCHAR(15)		NOT NULL,
	EMAIL				VARCHAR(100)	NOT NULL,
	CONTATO				VARCHAR(50)		NOT NULL
);

CREATE TABLE CONVENIO(
	CONVENIO_ID			INT				NOT NULL	PRIMARY KEY IDENTITY,
	TIPO				VARCHAR(20)		NOT NULL,
	VALOR_DESCONTO		DECIMAL(8,2)	
);

CREATE TABLE PRODUTO(
	PRODUTO_ID			INT				NOT NULL	PRIMARY KEY IDENTITY,
	PRODUTO				VARCHAR(20)		NOT NULL,
	PRECO				DECIMAL(8,2)	NOT NULL,
	DATA_VALIDADE		DATE,
	FORNECEDOR_ID		INT,

	FOREIGN KEY(FORNECEDOR_ID) REFERENCES FORNECEDOR(FORNECEDOR_ID)
);

CREATE TABLE FUNCIONARIO(
	FUNCIONARIO_ID		INT				NOT NULL	PRIMARY KEY IDENTITY,
	NOME				VARCHAR(50)		NOT NULL,
	CARGO				VARCHAR(50)		NOT NULL
);

CREATE TABLE PEDIDO(
	PEDIDO_ID			INT				NOT NULL	PRIMARY KEY IDENTITY,
	DATA_PEDIDO			DATE			NOT NULL,
	VALOR_TOTAL			DECIMAL(8,2)	NOT NULL,
	CLIENTE_ID			INT				NOT NULL,
	FORNECEDOR_ID		INT				NOT NULL,
	CONVENIO_ID			INT				NOT NULL,

	FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID),
	FOREIGN KEY(FORNECEDOR_ID) REFERENCES FORNECEDOR(FORNECEDOR_ID),
	FOREIGN KEY(CONVENIO_ID) REFERENCES CONVENIO(CONVENIO_ID)
);

CREATE TABLE ITEMPEDIDO(
	PEDIDO_ID			INT				NOT NULL,
	PRODUTO_ID			INT				NOT NULL,
	PRECO_UNITARIO		DECIMAL(8,2)	NOT NULL,
	QUANTIDADE			INT				NOT NULL,
	VALOR_TOTAL			DECIMAL(8,2)	NOT NULL,

	FOREIGN KEY(PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID),
	FOREIGN KEY(PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID)
);

-- INSERIR DADOS

INSERT INTO CLIENTE(CLIENTE,EMAIL,TELEFONE)VALUES
	('Rafael Barbosa Felicio','rbarbosabd@gmail.com','(14)98804-7973');

INSERT INTO FUNCIONARIO(NOME,CARGO)VALUES
	('Jovino do Amaral','Repositor'),
	('André Luiz','Vigilante');

INSERT INTO FORNECEDOR(RAZAO_SOCIAL,TELEFONE,EMAIL,CONTATO)VALUES
	('Mercado & Mercado Comercio LTDA.','(14)3232-1558','contato@supervarejo.com.br','Alberto Roberto');

INSERT INTO PRODUTO(PRODUTO,PRECO,DATA_VALIDADE,FORNECEDOR_ID)VALUES
	('Cerveja Imperio',2.99,'20-10-19',1),
	('Picanha',46.90,'09-09-19',1);

INSERT INTO CONVENIO(TIPO,VALOR_DESCONTO)VALUES
	('Particular',1.5);

BEGIN TRANSACTION TRA_PEDIDO;
INSERT INTO PEDIDO(
	DATA_PEDIDO,
	VALOR_TOTAL,
	CLIENTE_ID,
	FORNECEDOR_ID,
	CONVENIO_ID) 
	VALUES(
	GETDATE(),
	0.0,
	(SELECT CLIENTE_ID FROM CLIENTE WHERE CLIENTE='Rafael Barbosa Felicio'),
	(SELECT FORNECEDOR_ID FROM FORNECEDOR WHERE RAZAO_SOCIAL='Mercado & Mercado Comercio LTDA.'),
	(SELECT CONVENIO_ID FROM CONVENIO WHERE TIPO='Particular')
	);

INSERT INTO ITEMPEDIDO(
	PEDIDO_ID,
	PRODUTO_ID,
	PRECO_UNITARIO,
	QUANTIDADE,
	VALOR_TOTAL
	)VALUES(
		(SELECT IDENT_CURRENT('PEDIDO')),
		(SELECT PRODUTO_ID FROM PRODUTO WHERE PRODUTO='Cerveja Imperio'),
		(SELECT PRECO FROM PRODUTO WHERE PRODUTO='Cerveja Imperio'),
		2,
		2*(SELECT PRECO FROM PRODUTO WHERE PRODUTO='Cerveja Imperio')
	),
	(
		(SELECT IDENT_CURRENT('PEDIDO')),
		(SELECT PRODUTO_ID FROM PRODUTO WHERE PRODUTO='Picanha'),
		(SELECT PRECO FROM PRODUTO WHERE PRODUTO='Picanha'),
		2,
		2*(SELECT PRECO FROM PRODUTO WHERE PRODUTO='Picanha')
	);

	UPDATE PEDIDO SET
	VALOR_TOTAL= (SELECT SUM(VALOR_TOTAL) FROM ITEMPEDIDO WHERE PEDIDO_ID=(SELECT IDENT_CURRENT('PEDIDO')));

COMMIT TRANSACTION TRA_PEDIDO;
